[package]
name = "codepot"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
color-eyre = "0.6.3"
rand = "0.8.5"
scopeguard = "1.2.0"
tempfile = "3.12.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
